### ISSUE TITLE
Optimiser la fonction follow

### ISSUE THREAD

**Issue by phperrot** [fabrahaingo/joel#13]
La fonction follow procède actuellement ainsi: 
(1) entrée du nom de la personne qu'on souhaite suivre
(2) affichage des 3 dernières nominations au JO de la personne
(3) confirmation par l'utilisateur que c'est bien la personne qu'on souhaite suivre

Proposition de fluidification: 
(1) entrée le nom de la personne qu'on souhaite suivre
(2) si la personne existe sur jorfsearch, elle est suivi sans besoin de confirmation, sinon, message d'erreur

cela permettra de faciliter le travail d'ajout de personnes, notamment quand il y en a beaucoup ;)

**Comment by fabrahaingo** [comment]
La fonction a été implémentée [ici](https://redirect.teleparty.com/join/b2cb3b3781107443) ✅
