### ISSUE TITLE
Les liens vers les publications BOMI ne fonctionnent pas

### ISSUE THREAD

**Issue by phperrot** [fabrahaingo/joel#14]
**Contexte**

Jorfsearch agrège à la fois les nominations au JO et au Bulletin officiel du ministère de l'intérieur (BOMI). 

**Problème**

Cependant, il semble que les renvois JOEL vers ces publications ne fonctionnent pas. 

Exemple avec Mme Céline Cheval: sur Jorfsearch, le lien de la publication renvoyé sur Jorfsearch est https://bodata.steinertriples.ch/INTK2000525A.pdf 

alors que sur JOEL, on renseigne comme lien : 
https://www.legifrance.gouv.fr/jorf/id/INTK2000525A, qui naturellement ne fonctionne pas 

**Proposition de résolution:** 

dans formatSearchResults.js, ajouter une condition:  si source_name = BOMI, le lien créé est "https://bodata.steinertriples.ch/"& source_id & ".pdf"

**Comment by fabrahaingo** [comment]
Cette issue a été fix dans ce commit: https://github.com/fabrahaingo/joel/commit/141261652c56ce56ed4a7ec964b73c1d28f327af
