### ISSUE TITLE
Rendre insensible à la casse le listage des personnes suivies

### ISSUE THREAD

**Issue by phperrot** [fabrahaingo/joel#15]
**Situation**: les noms qui commencent par une minuscule (particules) se retrouvent lister à la fin
**Solution**: rendre la liste case insensitive

**Comment by fabrahaingo** [comment]
Réglé dans ce commit: https://github.com/fabrahaingo/joel/commit/831f3f6b5728273c72b2210c37a4dddc625f5c56 ✅

Il me semble que ce problème ne se produisait que lors de la suppression de contacts.
Le problème a donc été corrigé sur cette fonctionnalité uniquement.

Si le problème persiste ou qu'il existe autre part, feel free to reopen the issue 😇
