### ISSUE TITLE
Minimiser les données stockées

### ISSUE THREAD

**Issue by phperrot** [fabrahaingo/joel#16]
**Situation**: les pages entières de JORFSearch sont comparées
**Problème**: le principe de minimisation des données stockées devrait conduire à se contenter de stocker uniquement les informations nécessaires
**Solutions**: 
- Ne stocker que la dernière nomination et la comparer d'une fois à l'autre
OU
- Ne stocker que la date de la dernière nomination et voir si antérieure à date présente
OU 
- Ne stocker que le NOM + Prénom et regarder si cela apparaît sur la page JORFSearch de recherche par date (si oui, alors notif)

**Comment by fabrahaingo** [comment]
Cette issue a été résolue dans le commit suivant: https://github.com/fabrahaingo/joel/commit/235a04a16df93b6cfeb35f05c34db93cafdd1945 ✅

La première solution a été retenue en utilisant le champ `lastKnownPosition` qui ne stocke que la dernière publication au JO (contre tout l'historique auparavant).

Garder une trace de la dernière publication permet de vérifier plus rapidement/facilement si la MàJ d'une personne a été effectuée (lorsqu'une résolution de bug "à la main" s'impose 🥵).

Cela permet enfin de garder une séparation propre entre les scripts `updateDb.js` et `notifyUsers.js`. En effet, plus besoin de faire un appel à l'API de JORFSearch dans le second script car le strict nécessaire pour les notifications est stocké en base de données 👌
