### ISSUE TITLE
Ajouter nouvelles promotions ENA à la fonction ena.js

### ISSUE THREAD

**Issue by phperrot** [fabrahaingo/joel#19]
Dans l'attente de leurs noms, permettre à la promotion 21-22 d'être ajoutée (fonction ena puis "2022"), ainsi qu'à la promotion 22-23 ("2023")

**Comment by fabrahaingo** [comment]
Issue resolved here: https://github.com/fabrahaingo/joel/commit/49a1b7529d47bdab9f32afce641771770a3e47e1 ✅

21-22 is the `Germaine Tillion` promotion, therefore, I only added the "2023" promotion (2022-2023). Please remember to keep me posted when the promotion gets a name :)
