### ISSUE TITLE
Rendre cliquable les noms des personnes dont on reçoit des notifications

### ISSUE THREAD

**Issue by phperrot** [fabrahaingo/joel#25]
Le suivi d'institution/poste conduit à recevoir des notifications concernant des personnes qu'on ne connaît pas nécessairement. 
Aussi, serait-il utile de pouvoir rapidement savoir quel est le parcours de ces personne, en rendant leur nom cliquable, ce qui déclencherait la fonction "🔍 Rechercher" et afficherait les précédentes nominations. 

### ACTUELLEMENT: 

> ====================
> 
> Nouvelle publication pour les personnes suivies avec le tag sous-prefet:
> 
> Christophe Borgus
> 📝 A été nommé à:
> 👉 Sous-préfecture - Istres
> 🗓 Publié le:  1 septembre 2024 
> 🔗 Lien JO:  [cliquez ici](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000050171005)

### Je souhaiterais: 

> ====================
> 
> Nouvelle publication pour les personnes suivies avec le tag sous-prefet:
> 
> [Christophe Borgus](url) 
> 📝 A été nommé à:
> 👉 Sous-préfecture - Istres
> 🗓 Publié le:  1 septembre 2024 
> 🔗 Lien JO:  [cliquez ici](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000050171005)

où en cliquant sur le nom de la personne nommée, je déclenche la fonction "Rechercher" la concernant, ce qui m'afficherait ces nominations antérieures.

**Comment by fabrahaingo** [comment]
MR mergée. C'est désormais en production, je close.
